-- Create app_settings table (Singleton pattern, only row 1 used)
CREATE TABLE IF NOT EXISTS app_settings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_prefix TEXT DEFAULT 'INV-',
    next_invoice_seq INT DEFAULT 1000,
    default_payment_info TEXT, -- Zelle ID text
    default_payment_qr_url TEXT, -- URL to QR image
    owner_details JSONB DEFAULT '{"name": "Brandon P. Davis", "email": "brandon@brandonptdavis.com", "website": "brandonptdavis.com"}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default row if not exists
INSERT INTO app_settings (id, invoice_prefix, next_invoice_seq)
SELECT 1, 'INV-', 1000
WHERE NOT EXISTS (SELECT 1 FROM app_settings WHERE id = 1);

-- Create expenses table
CREATE TABLE IF NOT EXISTS expenses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    description TEXT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    category TEXT,
    receipt_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

-- Policies for app_settings (Admin access only, effectively authenticated users)
DROP POLICY IF EXISTS "Allow all for authenticated users on app_settings" ON app_settings;
CREATE POLICY "Allow all for authenticated users on app_settings"
ON app_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Policies for expenses
DROP POLICY IF EXISTS "Allow all for authenticated users on expenses" ON expenses;
CREATE POLICY "Allow all for authenticated users on expenses"
ON expenses FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Add performance indexes
CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(date);
CREATE INDEX IF NOT EXISTS idx_expenses_category ON expenses(category);
