-- Consolidated Fix for Finance Tables

-- 1. App Settings
CREATE TABLE IF NOT EXISTS app_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  next_invoice_seq INTEGER DEFAULT 1000,
  invoice_prefix TEXT DEFAULT 'INV-',
  default_payment_info TEXT, -- Zelle/Bank info
  default_payment_qr_url TEXT,
  business_name TEXT DEFAULT 'BRANDON P. DAVIS',
  business_address JSONB DEFAULT '{"street": "", "city": "", "state": "", "zip": "", "country": "USA"}',
  business_website TEXT DEFAULT 'www.brandonptdavis.com',
  invoice_footer_note TEXT DEFAULT 'Thank you for your business.'
);

-- Ensure RLS on app_settings
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON app_settings FOR SELECT USING (true);
CREATE POLICY "Allow admin full access" ON app_settings FOR ALL USING (true);


-- 2. Finance Categories & Expenses
CREATE TABLE IF NOT EXISTS expense_categories (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  type TEXT CHECK (type IN ('business', 'personal')) DEFAULT 'business'
);

CREATE TABLE IF NOT EXISTS expenses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  date DATE NOT NULL,
  description TEXT NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  category TEXT,
  receipt_url TEXT,
  is_recurring BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS recurring_expenses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  description TEXT NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  category TEXT,
  frequency TEXT CHECK (frequency IN ('monthly', 'yearly', 'weekly')) DEFAULT 'monthly',
  day_of_month INTEGER, -- 1-31
  last_generated_date DATE,
  active BOOLEAN DEFAULT true
);

ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow admin full access" ON expenses FOR ALL USING (true);

ALTER TABLE recurring_expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow admin full access" ON recurring_expenses FOR ALL USING (true);


-- 3. Time Entries & Invoices (Ensure they exist)
CREATE TABLE IF NOT EXISTS invoices (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  company_id UUID, -- Foreign key removed/optional for loose coupling or check separate table
  project_id UUID,
  number TEXT NOT NULL,
  issue_date DATE NOT NULL,
  due_date DATE NOT NULL,
  status TEXT DEFAULT 'draft',
  subtotal NUMERIC(10, 2) DEFAULT 0,
  tax_rate NUMERIC(5, 2) DEFAULT 0,
  tax_amount NUMERIC(10, 2) DEFAULT 0,
  total_amount NUMERIC(10, 2) DEFAULT 0,
  notes TEXT,
  pdf_url TEXT,
  payment_info TEXT,
  payment_qr_url TEXT
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  invoice_id UUID REFERENCES invoices(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  quantity NUMERIC(10, 2) NOT NULL DEFAULT 1,
  unit_price NUMERIC(10, 2) NOT NULL DEFAULT 0,
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS time_entries (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  project_id UUID,
  project_name TEXT,
  company_id UUID,
  date DATE NOT NULL,
  hours NUMERIC(5, 2) NOT NULL,
  description TEXT,
  billable BOOLEAN DEFAULT true,
  rate NUMERIC(10, 2),
  invoice_id UUID REFERENCES invoices(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'unbilled'
);

ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow admin full access" ON invoices FOR ALL USING (true);

ALTER TABLE invoice_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow admin full access" ON invoice_items FOR ALL USING (true);

ALTER TABLE time_entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow admin full access" ON time_entries FOR ALL USING (true);

-- 4. Insert Default Settings if Empty
INSERT INTO app_settings (id)
SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM app_settings WHERE id = 1);

-- 5. Seed Defaults
INSERT INTO expense_categories (name) VALUES 
('Software Subscription'), ('Office Supplies'), ('Travel'), ('Contractors'), ('Cloud Infrastructure')
ON CONFLICT (name) DO NOTHING;
