-- MASTER FIX V2.1: Fixed DROP POLICY syntax error
-- Run this to ensure ALL tables and columns exist.

-- 1. App Settings Table & Columns
CREATE TABLE IF NOT EXISTS app_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure all columns exist on app_settings
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS next_invoice_seq INTEGER DEFAULT 1000;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS invoice_prefix TEXT DEFAULT 'INV-';
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS default_payment_info TEXT;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS default_payment_qr_url TEXT;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS business_name TEXT DEFAULT 'BRANDON P. DAVIS';
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS business_address JSONB DEFAULT '{"street": "", "city": "", "state": "", "zip": "", "country": "USA"}';
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS business_website TEXT DEFAULT 'www.brandonptdavis.com';
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS invoice_footer_note TEXT DEFAULT 'Thank you for your business.';
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS default_hourly_rate NUMERIC(10, 2) DEFAULT 100.00;

-- Ensure RLS on app_settings
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access" ON app_settings;
CREATE POLICY "Allow public read access" ON app_settings FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow admin full access" ON app_settings;
CREATE POLICY "Allow admin full access" ON app_settings FOR ALL USING (true);

-- Initialize default settings if empty
INSERT INTO app_settings (id, business_name)
SELECT 1, 'BRANDON P. DAVIS'
WHERE NOT EXISTS (SELECT 1 FROM app_settings WHERE id = 1);


-- 2. Expense Categories (Fix RLS Warning)
CREATE TABLE IF NOT EXISTS expense_categories (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  type TEXT CHECK (type IN ('business', 'personal')) DEFAULT 'business'
);
ALTER TABLE expense_categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access categories" ON expense_categories;
CREATE POLICY "Allow public read access categories" ON expense_categories FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow admin modify categories" ON expense_categories;
CREATE POLICY "Allow admin modify categories" ON expense_categories FOR ALL USING (true);


-- 3. Invoices (Fix 400 Bad Request by ensuring columns exist)
CREATE TABLE IF NOT EXISTS invoices (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- Ensure columns
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS company_id UUID;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS project_id UUID;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS number TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS issue_date DATE;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS due_date DATE;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'draft';
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS subtotal NUMERIC(10, 2) DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS tax_rate NUMERIC(5, 2) DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(10, 2) DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS total_amount NUMERIC(10, 2) DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS pdf_url TEXT;
-- These describe the 400 error:
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS payment_info TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS payment_qr_url TEXT;

ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow admin full access invoices" ON invoices;
CREATE POLICY "Allow admin full access invoices" ON invoices FOR ALL USING (true);

-- 4. Invoice Items
CREATE TABLE IF NOT EXISTS invoice_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  invoice_id UUID REFERENCES invoices(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  quantity NUMERIC(10, 2) NOT NULL DEFAULT 1,
  unit_price NUMERIC(10, 2) NOT NULL DEFAULT 0,
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0
);
ALTER TABLE invoice_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow admin full access invoice_items" ON invoice_items;
CREATE POLICY "Allow admin full access invoice_items" ON invoice_items FOR ALL USING (true);

-- 5. Time Entries
CREATE TABLE IF NOT EXISTS time_entries (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  project_id UUID,
  project_name TEXT,
  company_id UUID,
  date DATE NOT NULL,
  hours NUMERIC(5, 2) NOT NULL,
  description TEXT,
  billable BOOLEAN DEFAULT true,
  rate NUMERIC(10, 2),
  invoice_id UUID REFERENCES invoices(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'unbilled'
);
ALTER TABLE time_entries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow admin full access time_entries" ON time_entries;
CREATE POLICY "Allow admin full access time_entries" ON time_entries FOR ALL USING (true);

-- 6. Expenses & Recurring
CREATE TABLE IF NOT EXISTS expenses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  date DATE NOT NULL,
  description TEXT NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  category TEXT,
  receipt_url TEXT,
  is_recurring BOOLEAN DEFAULT false
);
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow admin full access expenses" ON expenses;
CREATE POLICY "Allow admin full access expenses" ON expenses FOR ALL USING (true);

CREATE TABLE IF NOT EXISTS recurring_expenses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  description TEXT NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  category TEXT,
  frequency TEXT,
  day_of_month INTEGER,
  last_generated_date DATE,
  active BOOLEAN DEFAULT true
);
ALTER TABLE recurring_expenses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow admin full access recurring" ON recurring_expenses;
CREATE POLICY "Allow admin full access recurring" ON recurring_expenses FOR ALL USING (true);
