-- Add missing columns to portfolio_projects
ALTER TABLE public.portfolio_projects 
ADD COLUMN IF NOT EXISTS month INTEGER,
ADD COLUMN IF NOT EXISTS client_name TEXT,
ADD COLUMN IF NOT EXISTS role TEXT,
ADD COLUMN IF NOT EXISTS duration TEXT,
ADD COLUMN IF NOT EXISTS challenge TEXT,
ADD COLUMN IF NOT EXISTS solution TEXT,
ADD COLUMN IF NOT EXISTS key_features JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS metrics JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS team JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS testimonial JSONB DEFAULT NULL,
ADD COLUMN IF NOT EXISTS content JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS process JSONB DEFAULT '[]'::jsonb;
